name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Valhalla JDK
      run: |
        wget https://builds.shipilev.net/openjdk-jdk-valhalla/openjdk-jdk-valhalla-linux-x86_64-server.tar.xz
        mkdir -p $HOME/jdk
        tar -xvf openjdk-jdk-valhalla-linux-x86_64-server.tar.xz -C $HOME/jdk
        ls -l $HOME/jdk
        export JAVA_HOME=$HOME/jdk/jdk
        $JAVA_HOME/bin/java -version
    - name: Build with Maven
      run: |
        mvn --version
        mvn -B package --file pom.xml
